name: integrated_health_app
description: Integrated health app for patient education and consultation
publish_to: 'none'
version: 1.0.0+1dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.11.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
  crypto: ^3.0.3
  intl: ^0.18.1
  vector_math: ^2.1.4
  syncfusion_flutter_charts: ^24.1.41


  # State Management
  provider: ^6.1.1

  # UI & Utilities
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Storage & File Operations
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Image Operations
  image: ^4.1.3
  path: ^1.8.3

  # Export & Sharing
  share_plus: ^12.0.0
  permission_handler: ^12.0.1
  pdf: ^3.10.7

  # HTTP Client
  http: ^1.1.0

  # 3D Model Viewer
  webview_flutter: ^4.10.0

  # UI Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets folder
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/thyroid/anatomy/
    - assets/images/thyroid/diseases/graves/
    - assets/images/thyroid/diseases/hashimotos/
    - assets/images/thyroid/diseases/hypothyroid/
    - assets/images/thyroid/diseases/toxic_multinodular/
    - assets/images/thyroid/diseases/subacute/
    - assets/images/thyroid/diseases/cancer/
    - assets/images/model_thumbnails/

